# Generated by Django 4.2.1 on 2023-06-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
