# Generated by Django 4.2.2 on 2023-06-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_plato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='telefono',
        ),
    ]
