# Generated by Django 4.2.1 on 2023-06-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_formulario_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='telefono',
        ),
    ]
