# Generated by Django 4.2.2 on 2023-06-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_formulario_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='comentario',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='ap_materno',
            new_name='materno',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='ap_paterno',
            new_name='paterno',
        ),
    ]
