# Generated by Django 4.2.1 on 2023-06-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_rename_comentario_formulario_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plato',
            options={'ordering': ['categoria', 'nombre']},
        ),
        migrations.AddField(
            model_name='plato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='platos', verbose_name='Imagen'),
        ),
    ]
