# Generated by Django 4.2.1 on 2023-06-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_plato_options_plato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/platos', verbose_name='Imagen'),
        ),
    ]
