# Generated by Django 4.2.1 on 2023-06-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_plato_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=15)),
                ('precio', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/principal', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='plato',
        ),
    ]
