# Generated by Django 4.2.2 on 2023-06-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_principal_delete_plato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebestible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=15)),
                ('precio', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/bebestible', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=15)),
                ('precio', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/postre', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
