# Generated by Django 4.2.1 on 2023-06-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_bebestible_postre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principal',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'principal', 'verbose_name_plural': 'principales'},
        ),
    ]
