# Generated by Django 4.2.1 on 2023-06-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_principal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name': 'formulario', 'verbose_name_plural': 'formularios'},
        ),
        migrations.AlterField(
            model_name='bebestible',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bebestible',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postre',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postre',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='principal',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='principal',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
